### ISSUE TITLE
누군가 해줬으면 싶은거

### ISSUE THREAD

**Issue by 09pinetree** [09pinetree/TypingProject#5]
파일 위치 정리
-Ubuntu_test 폴더에 있는것들 폴더 밖으로 다 꺼내고 원본 코드 삭제하기
-wordspawn.h에 코드 다 있으니 wordspawn.cpp는 필요없는거 같은데 삭제후 구동해서 맞으면 원본에서도 삭제하기

linux 명령어 잘 아는사람?

**Comment by lhh1109** [comment]
다 처리했는데 오히려 좀 지저분한것같기도하구..
괜찮나?

**Comment by 09pinetree** [comment]
굳굳
그런데 main.cpp가 원본파일인데 그거 없애고 test.cpp를 main.cpp로 좀 바꿔줘
